"""UsageService — synchronous usage tracking (task 4.2 GREEN).

Writes synchronously within the request's DB session/transaction.
Failure is swallowed (logged as warning) so it never blocks a generation request.
"""
import logging
import uuid
from datetime import date
from uuid import UUID

from app.domain.entities import UsageEvent
from app.domain.ports.usage_repository import UsageRepository

logger = logging.getLogger(__name__)


class UsageService:
    def __init__(self, usage_repo: UsageRepository) -> None:
        self._repo = usage_repo

    async def record(
        self,
        user_id: UUID,
        tenant_id: UUID,
        template_id: UUID | None,
        generation_type: str,
        document_count: int,
    ) -> None:
        """Create a UsageEvent in the repository.

        Wraps the write in try/except — failure is logged as a warning
        but NEVER re-raised so the caller's request is unaffected.
        """
        event = UsageEvent(
            id=uuid.uuid4(),
            user_id=user_id,
            tenant_id=tenant_id,
            template_id=template_id,
            generation_type=generation_type,
            document_count=document_count,
        )
        try:
            await self._repo.create(event)
        except Exception as exc:  # noqa: BLE001
            logger.warning(
                "UsageService.record() failed — usage event not persisted. "
                "user_id=%s generation_type=%s error=%s",
                user_id,
                generation_type,
                exc,
            )

    async def get_current_month_usage(
        self,
        user_id: UUID,
        year: int,
        month: int,
    ) -> int:
        """Return total documents generated by `user_id` in the given month."""
        month_start = date(year, month, 1)
        return await self._repo.get_user_month_total(user_id=user_id, month_start=month_start)

    async def get_tenant_usage(
        self,
        year: int,
        month: int,
    ) -> dict:
        """Return tenant-wide usage: total + per-user breakdown.

        Returns:
            {
                "total": int,
                "by_user": [{"user_id": UUID, "total": int}, ...]
            }
        """
        month_start = date(year, month, 1)
        total = await self._repo.get_tenant_month_total(month_start=month_start)
        by_user = await self._repo.get_tenant_user_breakdown(month_start=month_start)
        return {"total": total, "by_user": by_user}
